name: ⚙️CICD
description: CICD only changes.
projects: ["EngagedAgility/1"]
type: "CICD"
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > The title should be short and descriptive.

- type: textarea
  attributes:
    label: Description
    description: A description of CICD changes or additions.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review or closing the issue.
    value: |
      ### List of items to do
      - [ ] An issue type has been added to this issue.
      - [ ] A priority label was added to this issue.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      Example:
        - #10 
        - #20
    description: |
      A list of issues related to this issue but are not a dependency.
  validations:
    required: false
