name: 🚧 Project Item
description: Create an issue for the project.
title: "🚧"
projects: ["EngagedAgility/1"]
body:
- type: textarea
  attributes:
    label: Description
    description: A description of the feature and/or change.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    description: Complete the following items before requesting a PR review or closing the issue.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
      - [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of issues that are dependencies of this issue and need to be completed first.
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      Example:
        - #10 
        - #20
    description: |
      A list of issues related to this issue but are not a dependency.
  validations:
    required: false
