name: 🔬 Research Item
description: Research only work. (This will never entail changes tot he source code of the project.)
projects: ["EngagedAgility/1"]
type: "Research"
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > 1. The title should be short and descriptive.
      > 2. Pull requests are not required or used for research issues.

- type: checkboxes
  attributes:
    label: Complete The Item Below
    options:
    - label: A priority label has been added to this issue.
      required: true

- type: textarea
  attributes:
    label: What To Research
    description: A detailed description of the research to perform.
  validations:
    required: true

- type: textarea
  attributes:
    label: Research Results
    description: This can be notes, links to resources, etc.
    placeholder: "Tip: You can drag and drop files here." 
  validations:
    required: false

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Research complete and issues created _(if needed)_.
      - [ ] If any issues were created, they have been added to the _**Related Work**_ section below.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of related issues that are not a dependency.
  validations:
    required: false
