name: 🔬 Research Item
description: Create an issue to perform research.
labels: ["research"]
projects: ["EngagedAgility/1"]
title: "🔬"
body:
- type: markdown
  attributes:
    value: "‼️NOTE‼️: Pull requests are not required or used for research issues."

- type: textarea
  attributes:
    label: What To Research
    description: A detailed description of the research to perform.
  validations:
    required: true

- type: textarea
  attributes:
    label: Research Results
    description: This can be notes, links to resources, etc.
    placeholder: "Tip: You can drag and drop files here." 
  validations:
    required: false

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Research complete and issues created _(if needed)_.
      - [ ] If any issues were created, they have been added to the _**Related Work**_ section below.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: ToDo Items
    value: |
      ### The items to complete to satisfy the Definition of Done.
      - [ ] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: Issue Dependencies
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of dependencies that need to be finished first.
  validations:
    required: false

- type: textarea
  attributes:
    label: Related Work
    placeholder: |
      Example:
        - #10
        - #20
    description: |
      A list of related issues that are not a dependency.
  validations:
    required: false
