name: 📉 Tech Debt
description: Work involving improvements and refactoring of code to reduce technical debt and development costs. (Does not add features or change behavior.)
projects: ["EngagedAgility/1"]
type: "Tech-Debt"
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > The title should be short and descriptive.

- type: checkboxes
  attributes:
    label: Complete The Items Below
    options:
    - label: An issue type has been added to this issue. 
      required: true
    - label: A priority label has been added to this issue.
      required: true

- type: textarea
  attributes:
    label: Description
    description: A description of the feature.
  validations:
    required: true

- type: textarea
  attributes:
    label: Acceptance Criteria
    description: The items to complete to satisfy the Definition of Done.
    value: |
      ### The items to complete to satisfy the Definition of Done.
  validations:
    required: true
    render: markdown

- type: textarea
  attributes:
    label: QA Testing Notes
    placeholder: Add any additional notes for QA testing here.
    description: Additional information for QA testing.
  validations:
    required: false
